### ISSUE TITLE
Example _index.md has image as a .jpeg

### ISSUE THREAD

**Issue by jeremiah** [gevhaz/hugo-theme-notrack#12]
But I'm pretty sure it is a png. :-)

`exampleSite/static/hugo_grotius.png`

This means the fine photograph does not show up in the index page which is unfortunate.

**Comment by gevhaz** [comment]
Are you sure? The image displays fine for me. You mean on the "Home" tab, right?

**Comment by gevhaz** [comment]
I'll close for now. Please re-open if you still think there is a problem with the images.
