### ISSUE TITLE
Mastodon verification requires rel="me" in anchor

### ISSUE THREAD

**Issue by jtkristoff** [gevhaz/hugo-theme-notrack#14]
For the Mastodon social link, it would be nice to be able to add a rel="me" tag into the anchor link ?  This is used to perform link verification on the associated Mastodon account.  More detail can be found here:  https://docs.joinmastodon.org/user/profile/

This way I don't have to hack up the theme to much myself to add this in.  Thanks kindly.

**Comment by gevhaz** [comment]
Seems good to add. Thank you for the suggestion. Do you know of any downsides to adding it to all other social links as well? I think it makes sense for more or less all of them, and I don't think it hurts.

**Comment by jtkristoff** [comment]
I can't think of any serious problems this would present.  It seems sensible to just add it to all of social media links with the only downside it is a few extra bytes that go unused.  I can't imagine anyone getting too upset about that.

**Comment by gevhaz** [comment]
I added it to the master branch. `git pull` should give you the changes. Let me know if there are any issues.
