### ISSUE TITLE
Demo Page? Sticky< Header?

### ISSUE THREAD

**Issue by illupino** [gevhaz/hugo-theme-notrack#18]
Hi,

is there anywhere a demo page active so that I can check it out? 

Does notrack have a sticky header? Such a fixed top navigation is absolutely mandatory for me and I'd like to ask prior to using a lot of time editing. thx.

**Comment by gevhaz** [comment]
I'm afraid there's neither.

I'm considering using my GitHub Pages page as an example of the theme. For now I'll update the documentation (see [here](https://github.com/gevhaz/hugo-theme-notrack#try-it-out-yourself)). It's very easy to get an example website up and running locally, if you know that it's available.

Might be good to have a sticky header as a choice but I think it can be hard to develop. If you're interested in either feature, you can open issues for a specific one as a feature request. I'll close this as I've answered the questions.
