### ISSUE TITLE
Fail to build after hugo update

### ISSUE THREAD

**Issue by tvlpirb** [gevhaz/hugo-theme-notrack#24]
The exampleSite is failing to render with the following output:
```
Start building sites … 
hugo v0.112.3+extended linux/amd64 BuildDate=unknown
WARN 2023/05/28 22:46:59 The "twitter_simple" shortcode will soon require two named parameters: user and id. See "/home/talhah/notrack/exampleSite/content/blog/rich-content.md:26:1"
Built in 142 ms
Error: error building site: "/home/talhah/notrack/exampleSite/content/contact.md:10:1": failed to render shortcode "contact-box": failed to process shortcode: "/home/talhah/notrack/layouts/shortcodes/contact-box.html:3:29": execute of template failed: template: shortcodes/contact-box.html:3:29: executing "shortcodes/contact-box.html" at <.Get>: Get is not a method but has arguments
```

I believe it's to do with this API change [https://github.com/gohugoio/hugo/issues/10862](https://github.com/gohugoio/hugo/issues/10862)

I'm not sure how Hugo works exactly so if anyone has an idea how to fix this go ahead. Whatever I've tried hasn't worked.

**Comment by gevhaz** [comment]
Hi @tvlpirb, I appreciate the bug report :slightly_smiling_face: 

I can reproduce the issue on version 0.112.3 of Hugo (it was still working on 0.111.3).

I will look into it. Thanks for the research.

**Comment by gevhaz** [comment]
It should work again now
