### ISSUE TITLE
Add demo site

### ISSUE THREAD

**Issue by iwtga** [gevhaz/hugo-theme-notrack#26]
Adding a demo site would help people know exactly how the theme looks. Since setting this theme locally and following all the instructions just to get a glimpse of how all the pages look is a long task.

It would be better if you can try hosting this theme on GitHub pages (its free). All major themes have a demo page associated with them and it would be a great plus.

Thanks, looking forward for a demo site:)........

**Comment by gevhaz** [comment]
Hi, thanks for the request. I considered having a demo site, but concluded that it's not something I want to maintain. For one thing, I want to keep my GitHub Pages domain name available for more personal use. I am also content with the users that I do get, without feeling a need to market and get more.

**Comment by gevhaz** [comment]
Also see #7
