### ISSUE TITLE
Adding a Custom Favicon

### ISSUE THREAD

**Issue by alibbosca** [gevhaz/hugo-theme-notrack#3]
Hi! 

I really loved the theme and would firstly like to thank you for it. So, I am not that good with Hugo and wondered how I can add a custom favicon to the theme as I couldn't find anything relating to it in the documentation. I would greatly appreciate it if you could help or at least direct me towards a source I could find how to do so. Thx!

**Comment by gevhaz** [comment]
Thank you :) I'm glad you like it.

By favicon, do you mean the social links? There is a little bit about it in the Readme, [here](https://github.com/gevhaz/hugo-theme-notrack#user-content-how-to-display-social-links). 64 social resources are built into the theme, so you could do something like:

```
params:
  social:
    github: <your github username>
```

in your config.yaml. You can replace `github` with the site you want. The keywords are found in `data/notrack/social.yaml` as the least indented line in each entry in the file. The first few are `github`, `linkedin` and `twitter`, and the rest follow the same pattern. 

If you want to add something other than the built-in ones, you can add another entry in that file, in the same style as the other ones. `prefix` should be the part of an URL that goes before your username, and `class` should be the code word for the icon you want from AwesomeFonts. You can find it at their website. For example for this icon for GitHub, you can see that the classes should be "fab fa-github" https://fontawesome.com/v5.15/icons/github?style=brands . You can search around the site and find the one you want. 

Please ask if you need any more help!

**Comment by gevhaz** [comment]
Apparently a favicon is the icon next to the page title in the tab. Sorry about the misunderstanding. In case you're interested, there's now an example in the README and in the example site. I consider the issue resolved now so I'll close.

Thanks to @albinahlback for the contribution!
