### ISSUE TITLE
Categories display in Blog broken after Hugo upgrade from 0.119.0 to 0.120.0

### ISSUE THREAD

**Issue by founfabug** [gevhaz/hugo-theme-notrack#30]
## Description
The **Categories** display in **Blog** appears broken after Hugo upgrade from 0.119.0 to 0.120.0

- Repeatable
- Tested in Firefox and IRON
- Rendered HTML is noticeably different

Discovered in Hugo 0.120.4
Working in Hugo 0.119.0
Fails in Hugo 0.120.0

## Install
On Windows 10, per readme:

```
If you want to try out the theme with an example page, do the following:

$ git clone https://github.com/gevhaz/hugo-theme-notrack
$ mv hugo-theme-notrack notrack
$ cd notrack/exampleSite/
$ hugo server -D --themesDir ../..
```

## HTML render from Hugo 0.119.0
![119](https://github.com/gevhaz/hugo-theme-notrack/assets/65840268/630a2235-4c82-47ab-b735-c56b28f7843c)
## HTML render from Hugo 0.120.0
![120](https://github.com/gevhaz/hugo-theme-notrack/assets/65840268/1a2f4920-118f-48bf-90c9-6264122d8802)

_Thank you_

**Comment by gevhaz** [comment]
Caused by https://github.com/gohugoio/hugo/issues/10876

**Comment by gevhaz** [comment]
Thanks for the high quality bug report @founfabug :)

The issue should be resolved now, but please reopen if you find any remaining issues.

**Comment by founfabug** [comment]
Confirmed working as expected with:

- Hugo 0.120.4
- Hugo 0.120.0
- Hugo 0.119.0

Thank you (fabulous demo site BTW)
